kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "httpd.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "httpd.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "httpd.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  path: {{ .Values.service.path }}
  port:
    targetPort: {{ .Values.service.port }}
